[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
ffi = true
remappings = [
    # OpenZeppelin contracts mapping (must be first to override conflicts)
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
    # Uniswap core and periphery
    "v3-core/=lib/v3-core/",
    "v3-periphery/=lib/v3-periphery/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    # V4 (temporarily commented out to isolate V3 issues)
    # "v4-core/=lib/v4-core/",
    # "v4-periphery/=lib/v4-periphery/",
    # Other dependencies
    "forge-std/=lib/forge-std/src/",
    "solmate/=lib/v4-core/lib/solmate/src/",
    "prb-math/=lib/prb-math/src/"
]
fs_permissions = [
    { access = "read-write", path = ".forge-snapshots/" }, 
    { access = "read", path = "./" }, 
    { access = "read", path = "./out" }
]
# solc_version = "0.8.24"
solc = "0.8.28"
evm_version = "cancun"
bytecode_hash = "none"
cbor_metadata = false
optimizer = true
optimizer_runs = 50
via_ir = true

# Enhanced Error Reporting
verbosity = 3  # More verbose output
show_progress = true
color = "auto"

# Linting and Warnings
extra_output = ["storageLayout", "devdoc", "userdoc"]
ignored_error_codes = []  # Don't ignore any errors
deny_warnings = false  # Set to true in CI

# Gas Configuration
gas_reports = ["*"]
gas_reports_ignore = []

# Testing Configuration  
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 15 }

# Development Profile (more strict)
[profile.dev]
src = "src"
out = "out"
libs = ["lib"]
verbosity = 4
deny_warnings = true
show_progress = true
extra_output_files = ["abi", "evm.assembly", "storageLayout"]

# CI Profile (most strict)
[profile.ci]
src = "src" 
out = "out"
libs = ["lib"]
verbosity = 4
deny_warnings = true
show_progress = true
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 20 }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config